version: "3"
services:
  node:
    build: ./docker/node
    volumes:
      - ./app:/home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
  mongodb:
    build: ./docker/mongodb
    volumes:
      - E:\Node\chatio\docker\mongodb\db:/data/db
    ports:
      - "27017:27017"
  redis:
    build: ./docker/redis